//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lib03.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lib03.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &lt;PCode&gt;&lt;Instr Part1=&quot;0&quot; Part2=&quot;0&quot; Part3=&quot;-1&quot; Name=&quot;pushImm&quot; ArgPart3=&quot;0&quot; Arg16=&quot;0&quot; Arg32=&quot;1&quot; Syscall=&quot;0&quot; Gosub=&quot;0&quot; UnconditionalBranch=&quot;0&quot; ConditionalBranch=&quot;0&quot; NeverReturn=&quot;0&quot; GosubRet=&quot;0&quot; /&gt;&lt;Instr Part1=&quot;0&quot; Part2=&quot;1&quot; Part3=&quot;-1&quot; Name=&quot;pushImm&quot; ArgPart3=&quot;0&quot; Arg16=&quot;0&quot; Arg32=&quot;1&quot; Syscall=&quot;0&quot; Gosub=&quot;0&quot; UnconditionalBranch=&quot;0&quot; ConditionalBranch=&quot;0&quot; NeverReturn=&quot;0&quot; GosubRet=&quot;0&quot; /&gt;&lt;Instr Part1=&quot;0&quot; Part2=&quot;2&quot; Part3=&quot;0&quot; Name=&quot;pushFromPSp&quot; ArgPart3=&quot;0&quot; Arg16=&quot;1&quot; Arg32=&quot;0&quot; Syscall=&quot;0&quot; Gosub=&quot;0&quot; UnconditionalBranch=&quot;0&quot;  [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PCode {
            get {
                return ResourceManager.GetString("PCode", resourceCulture);
            }
        }
    }
}
