//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KH2Exfe.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KH2Exfe.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   kh2_file_dumper.exe %SRC%\KH2 -dT
        ///PAUSE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Cmd_Falo {
            get {
                return ResourceManager.GetString("Cmd_Falo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   kh2fmarc extract %SRC% exports 000al.idx 000bb.idx 000ca.idx 000dc.idx 000di.idx 000eh.idx 000es.idx 000hb.idx 000he.idx 000lk.idx 000lm.idx 000mu.idx 000nm.idx 000po.idx 000tr.idx 000tt.idx 000wi.idx 000wm.idx 000gumi.idx
        ///
        ///kh2fmarc extract_w_idx_filelist %SRC% exports filelist.txt
        ///
        ///pause に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Cmd_kkdf2 {
            get {
                return ResourceManager.GetString("Cmd_kkdf2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   kh2fmarc extract %SRC% exports 000al.idx 000bb.idx 000ca.idx 000dc.idx 000di.idx 000eh.idx 000es.idx 000hb.idx 000he.idx 000lk.idx 000lm.idx 000mu.idx 000nm.idx 000po.idx 000tr.idx 000tt.idx 000wi.idx 000wm.idx 000gumi.idx
        ///
        ///kh2fmarc extract_w_idx %SRC% exports %names%
        ///
        ///pause に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Cmd_kkdf2Sel {
            get {
                return ResourceManager.GetString("Cmd_kkdf2Sel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KH2Dump.exe %SRC%\KH2
        ///PAUSE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Cmd_yaz0r {
            get {
                return ResourceManager.GetString("Cmd_yaz0r", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KH2Dump.exe %SRC%
        ///PAUSE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Cmd_yaz0r04 {
            get {
                return ResourceManager.GetString("Cmd_yaz0r04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap FINDFILE16 {
            get {
                object obj = ResourceManager.GetObject("FINDFILE16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Flag_blueHS {
            get {
                object obj = ResourceManager.GetObject("Flag_blueHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Flag_greenHS {
            get {
                object obj = ResourceManager.GetObject("Flag_greenHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Flag_redHS {
            get {
                object obj = ResourceManager.GetObject("Flag_redHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap GoLtrHS {
            get {
                object obj = ResourceManager.GetObject("GoLtrHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap idr_dll {
            get {
                object obj = ResourceManager.GetObject("idr_dll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap openfolderHS {
            get {
                object obj = ResourceManager.GetObject("openfolderHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   〰愰⹬摩൸《〰扢椮硤਍〰挰⹡摩൸《〰捤椮硤਍〰搰⹩摩൸《〰桥椮硤਍〰攰⹳摩൸《〰畧業椮硤਍〰栰⹢摩൸《〰敨椮硤਍〰氰⹫摩൸《〰浬椮硤਍〰洰⹵摩൸《〰浮椮硤਍〰瀰⹯摩൸《〰牴椮硤਍〰琰⹴摩൸《〰楷椮硤਍〰眰⹭摩൸《戰瑡汴⹥楢൮《挰浯潭⹮摢൸《攰晦捥⹴慢൲《漰橢湥牴⹹楢൮《瀰潲牧獥⹳楢൮《猰獹整⹭楢൮《眰牯摬潰湩⹴楢൮《猳獹整⹭楢൮《氷捯污敳⹴楢൮ㄊ猲畯摮湩潦戮牡਍㐱業獳潩⹮慢൲ㄊ樵杩慳⹷楢൮㜊氰湡楤杮戮牡਍杢⽭畭楳っ〱戮浧਍杢⽭畭楳っㄱ戮浧਍杢⽭畭楳っ㈱戮浧਍杢⽭畭楳っ㌱戮浧਍杢⽭畭楳っ㐱戮浧਍杢⽭畭楳っ㔱戮浧਍杢⽭畭楳っ㘱戮浧਍杢⽭畭楳っ㜱戮浧਍杢⽭畭楳っ㠱戮浧਍杢⽭畭楳っ㤱戮浧਍杢⽭畭楳っ〵戮浧਍杢⽭畭楳っㄵ戮浧਍杢⽭畭楳っ㈵戮浧਍杢⽭畭楳っ㌵戮浧਍杢⽭畭楳っ㐵戮浧਍杢⽭畭楳っ㔵戮浧਍杢⽭畭楳っ㘵戮浧਍杢⽭畭楳っ㜵戮浧਍杢⽭畭楳っ㤵戮浧਍杢⽭畭楳っ〶戮浧਍杢⽭畭楳っㄶ戮浧਍杢⽭畭楳っ㈶戮浧਍杢⽭畭楳っ㌶戮浧਍杢⽭畭楳っ㐶戮浧਍杢⽭畭楳っ㔶戮浧਍杢⽭畭楳っ㘶戮浧਍杢⽭畭楳っ㜶戮浧਍杢⽭畭楳っ㠶戮浧਍杢⽭畭楳っ㤶戮浧਍杢⽭畭楳っㄸ戮浧਍杢⽭畭楳っ㈸戮浧਍杢⽭畭楳っ㐸戮浧਍杢⽭畭楳っ㔸戮浧਍杢⽭畭楳っ㜸戮浧਍杢⽭ [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OutFalo {
            get {
                return ResourceManager.GetString("OutFalo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   000al.idx
        ///000bb.idx
        ///000ca.idx
        ///000dc.idx
        ///000di.idx
        ///000eh.idx
        ///000es.idx
        ///000gumi.idx
        ///000hb.idx
        ///000he.idx
        ///000lk.idx
        ///000lm.idx
        ///000mu.idx
        ///000nm.idx
        ///000po.idx
        ///000tr.idx
        ///000tt.idx
        ///000wi.idx
        ///000wm.idx
        ///00battle.bin
        ///00common.bdx
        ///00effect.bar
        ///00objentry.bin
        ///00progress.bin
        ///00worldpoint.bin
        ///03system.bin
        ///07localset.bin
        ///12soundinfo.bar
        ///14mission.bar
        ///15jigsaw.bin
        ///50gumientry.bin
        ///60gb_effect.bar
        ///70landing.bar
        ///eventviewer.bar
        ///libretto-bb.bar
        ///libretto-ca.bar
        ///libretto-dc.bar
        ///libretto-eh.bar        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Outkkdf2 {
            get {
                return ResourceManager.GetString("Outkkdf2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   000al.idx
        ///000bb.idx
        ///000ca.idx
        ///000dc.idx
        ///000di.idx
        ///000eh.idx
        ///000es.idx
        ///000gumi.idx
        ///000hb.idx
        ///000he.idx
        ///000lk.idx
        ///000lm.idx
        ///000mu.idx
        ///000nm.idx
        ///000po.idx
        ///000tr.idx
        ///000tt.idx
        ///000wi.idx
        ///000wm.idx
        ///00battle.bin
        ///00common.bdx
        ///00effect.bar
        ///00font.bar
        ///00fontimg.bar
        ///00objentry.bin
        ///00place.bin
        ///00progress.bin
        ///00sysrc.bar
        ///00system.bin
        ///00worldpoint.bin
        ///03system.bin
        ///07localset.bin
        ///12soundinfo.bar
        ///14mission.bar
        ///15jigsaw.bin
        ///50gumientry.bin
        ///60gb_effect.bar
        ///70landing.bar
        ///eventviewer.bar
        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Outyaz0r04 {
            get {
                return ResourceManager.GetString("Outyaz0r04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap WebInsertHyperlinkHS {
            get {
                object obj = ResourceManager.GetObject("WebInsertHyperlinkHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
