//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace khiiMapv.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("khiiMapv.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap ActualSizeHS {
            get {
                object obj = ResourceManager.GetObject("ActualSizeHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   ■	0	1	2	3	4	5	6	7	8	9	＋	－	×	A	B	C	D	E	F	G
        ///H	I	J	K	L	M	N	O	P	Q	R	S	T	U	V	W	X	Y	Z	！	？
        ///％	／	※	、	。	，	．	・	：	…	-	ー	～		〝	〟	（	）	「	」	『
        ///』	“	”	［	］	＜	＞	－	－	＃	♪	→	←	全	合	成	半	○	×	△	□
        ///↑	↓	→	←	?	?	?	?	?	?	?	?	?	?	★	☆	l	a	y	t	i
        ///o	n	r	■	前	選	一	あ	い	う	え	お	か	き	く	け	こ	さ	し	す	せ
        ///そ	た	ち	つ	て	と	な	に	ぬ	ね	の	は	ひ	ふ	へ	ほ	ま	み	む	め	も
        ///や	ゆ	よ	ら	り	る	れ	ろ	わ	を	ん	が	ぎ	ぐ	げ	ご	ざ	じ	ず	ぜ	ぞ
        ///だ	ぢ	づ	で	ど	ば	び	ぶ	べ	ぼ	ぱ	ぴ	ぷ	ぺ	ぽ	ぁ	ぃ	ぅ	ぇ	ぉ	ゃ
        ///ゅ	ょ	っ	ア	イ	ウ	エ	オ	カ	キ	ク	ケ	コ	サ	シ	ス	セ	ソ	タ	チ	ツ
        ///テ	ト	ナ	ニ	ヌ	ネ	ノ	ハ	ヒ	フ	ヘ	ホ	マ	ミ	ム	メ	モ	ヤ	ユ	ヨ	ラ
        ///リ	ル	レ	ロ	ワ	ヲ	ン	ガ	ギ	グ	ゲ	ゴ	ザ	ジ	ズ	ゼ	ゾ	ダ	ヂ	ヅ	 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EVTjp0 {
            get {
                return ResourceManager.GetString("EVTjp0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ■	■	■	■	■	■	■	■	■	■	■	■	■	■	■	■	■	■	■	■	■
        ///■	■	■	■	■	■	■	■	■	■	■	■	■	■	■	■	■	■	■	誠	納
        ///泡	程	析	遮	戒	井	及	模	算	霧	熟	＃	鈍	賭	欺	鹿	式	炸	裂	索	詮
        ///眩	罠	千	塗	羽	柵	緊	粗	何	俺	行	世	界	紀	事	前	符	来	見	一	絡
        ///分	寂	心	賃	言	物	知	外	君	私	宛	今	男	島	老	緒	幕	処	菓	場	鎖
        ///食	夢	女	賞	所	者	時	消	探	当	無	儀	話	鍵	捜	中	目	公	声	謎	間
        ///為	鍵	密	闇	掌	僕	留	句	般	誰	聞	連	夫	扉	統	顔	丈	少	我	他	立
        ///合	助	対	刀	侮	辱	秘	通	頼	冒	帰	刑	夜	絶	船	即	方	込	全	良	忘
        ///凱	追	旅	起	険	供	抜	遠	最	感	役	各	入	旋	遂	日	欠	堅	主	会	向
        ///年	早	別	褒	宝	変	度	後	星	授	矢	配	現	覚	選	急	二	居	座	願	勝
        ///怪	漁	鼻	影	違	離	遅	訣	繋	視	勇	笑	奪	馳	々	切	厄	父	犬	白	跳
        ///祝	仮	強	押	仲	面	毛	回	倒	拒	持	画	近	戻	望	負	傷	刀	拐	優 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EVTjp1 {
            get {
                return ResourceManager.GetString("EVTjp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   金	情	令	貸	突	円	妙	録	笛	境	田	秀	根	相	終	広	乗	駄	的	宇	邪
        ///冷	投	呼	葉	暴	百	黄	新	町	喰	捨	避	妃	安	頃	枚	尻	没	嵐	季	節
        ///困	悔	汽	暗	排	体	状	況	流	条	希	店	被	再	第	僧	練	習	末	契	果
        ///可	族	滝	反	組	多	協	支	念	了	誘	卒	業	泳	嬢	灯	賊	張	嫌	員	隊
        ///争	服	黒	→	←	口	忙	映	写	砂	漠	妖	精	粉	存	在	♪	野	郎	降	想
        ///像	数	激	国	務	操	縦	洞	整	鼓	室	屋	貝	騒	問	題	簡	単	関	係	祈
        ///辺	昔	匹	母	礼	任	腹	輩	侵	非	距	学	愚	点	活	躍	臣	喜	板	岩	茶
        ///異	線	沈	迷	働	秩	序	規	＃	貴	送	静	初	六	払	客	薬	暮	青	諸	舵
        ///旗	廃	墟	陰	奇	懐	染	横	響	逆	苦	威	廷	育	群	悟	奥	査	慎	好	利
        ///有	住	平	和	壁	瞬	難	干	渉	乱	窟	窓	研	究	香	台	ヶ	救	態	村	驚
        ///伸	咲	繁	価	甘	獲	案	誤	賛	舞	迎	保	識	庫	慣	冠	魅	増	狐	握	班
        ///散	転	弁	至	律	亡	万	油	等	席	興	局	位	図	宿	申	憎	焼	惑	凶 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EVTjp2 {
            get {
                return ResourceManager.GetString("EVTjp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   統	観	触	揺	標	到	拐	超	測	弾	富	留	易	文	献	採	漂	語	造	稼	改
        ///能	比	較	区	訪	往	混	沌	底	原	墓	普	絵	額	又	暇	縮	呪	掛	慮	＃
        ///癒	階	鐘	描	秋	冬	夏	泊	東	展	戸	舷	浮	毒	氷	幻	胃	腸	誕	椅	館
        ///廊	堂	斎	玉	械	砲	聖	針	春	冬	南	山	川	谷	渓	崖	岸	t	棺	門	月
        ///丘	吊	拷	倉	蔵	浜	江	淵	溝	庭	園	峡	潮	段	柱	基	h	汝	楼	拝	草
        ///竹	沼	層	虚	噴	交	花	輝	護	巧	師	首	術	飾	神	箱	輪	腕	手	防	御
        ///撃	攻	小	定	認	法	技	巨	樹	効	系	運	半	字	鉱	三	型	耐	速	設	低
        ///共	g	側	阻	両	級	殻	圧	亜	劣	胴	脚	独	射	偉	勘	頂	戴	忍	素	b
        ///＆	則	四	掲	板	登	孫	締	憐	鮮	歪	叫	推	旧	臨	奈	摩	y	細	肉	因
        ///財	疲	婆	省	寒	沢	商	却	派	盛	泥	棄	?	代	晩	枯	期	譲	晴	卑	越
        ///縁	権	極	磨	替	宣	歓	績	繰	栄	淑	幾	杯	紳	候	壁	杭	補	懲	酬	勤
        ///怯	余	労	匂	罰	糸	辛	棟	課	荷	頑	恥	酷	随	醜	詞	償	棒	隣	励 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EVTjp3 {
            get {
                return ResourceManager.GetString("EVTjp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap ROCKET {
            get {
                object obj = ResourceManager.GetObject("ROCKET", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap search4files {
            get {
                object obj = ResourceManager.GetObject("search4files", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   ■	0	1	2	3	4	5	6	7	8	9	＋	－	×	A	B	C	D	E	F	G	H	I	J	K	L	M	N
        ///O	P	Q	R	S	T	U	V	W	X	Y	Z	！	？	％	／	※	、	。	．	，	・	：	…	-	－	～	&apos;
        ///〝	〟	（	）	「	」	『	』	“	”	〔	〕	＜	＞	－	－	＠	→	←	♪	全	合	成	半	○	×	△	□
        ///↑	↓	→	←	？	？	？	？	？	？	？	？	？	？	★	☆	Ⅲ	？	？	Ⅹ	？	？	？	？	？	前	選	一
        ///あ	い	う	え	お	か	き	く	け	こ	さ	し	す	せ	そ	た	ち	つ	て	と	な	に	ぬ	ね	の	は	ひ	ふ
        ///へ	ほ	ま	み	む	め	も	や	ゆ	よ	ら	り	る	れ	ろ	わ	を	ん	が	ぎ	ぐ	げ	ご	ざ	じ	ず	ぜ	ぞ
        ///だ	ぢ	づ	で	ど	ば	び	ぶ	べ	ぼ	ぱ	ぴ	ぷ	ぺ	ぽ	ぁ	ぃ	ぅ	ぇ	ぉ	ゃ	ゅ	ょ	っ	ア	イ	ウ	エ
        ///オ	カ	キ	ク	ケ	コ	サ	シ	ス	セ	ソ	タ	チ	ツ	テ	ト	ナ	ニ	ヌ	ネ	ノ	ハ	ヒ	フ	ヘ	ホ	マ	ミ
        ///ム	メ	モ	ヤ	ユ	ヨ	ラ	リ	ル	レ	ロ	ワ	ヲ	ン	ガ	ギ	グ	ゲ	ゴ	ザ	ジ	ズ	ゼ	ゾ	ダ	ヂ	ヅ	デ        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYSjp {
            get {
                return ResourceManager.GetString("SYSjp", resourceCulture);
            }
        }
    }
}
